### ISSUE TITLE
Postgres user permissions

### ISSUE THREAD

**Issue by dbrenecki** [servian/TechChallengeApp#29]
### Subject of the issue

AWS RDS using Postgres 10.4 permissions issue.

`pq: permission denied for tablespace pg_default`

### Your environment

* Application v0.3.6
* Golang go1.9.4 linux/amd64
* Postgres 10.4

### Steps to reproduce

Adding the app files to an EC2 instance to communicate with the Postgres 10.4 RDS database and running `./TechTestAppLinux updatedb -s`

### Expected behaviour

```
Dropping and recreating table: tasks
DROP TABLE IF EXISTS tasks CASCADE
CREATE TABLE tasks ( id SERIAL PRIMARY KEY, completed boolean NOT NULL, priority integer NOT NULL, title text NOT NULL)
Seeding table with data
```

### Actual behaviour

```
Dropping and recreating database: <dbname>
DROP DATABASE IF EXISTS <dbname>
CREATE DATABASE <dbname>
WITH 
OWNER = postgres
ENCODING = 'UTF8'
LC_COLLATE = 'en_US.utf8'
LC_CTYPE = 'en_US.utf8'
TABLESPACE = pg_default
CONNECTION LIMIT = -1
TEMPLATE template0;
pq: permission denied for tablespace pg_default
```

### Workaround
Use Postgres 9.6 for the RDS to solve this issue.

**Comment by david773** [comment]
I did some testing and all versions should work even the latest one (10.4).  The source of this issue actually comes from the `/TechTestApp updatedb` command as it first drops the db if it exists then tries to recreate it but can't.  If you ran this command you will need to recreate your db then make sure the command includes the `-s` tag e.g. `./TechTestApp updatedb -s`

**Comment by jnorback** [comment]
I though that the intention was "to create a database, tables, and seed it with test data" with the ./TechTestApp updatedb command. I fail to see what use the -s tag would have for this test as there wont be any data in the DB to test with...?

From the documentation:
./TechTestApp updatedb to create a database, tables, and seed it with test data. Use -s to skip creating the database.

**Comment by david773** [comment]
The 'updatedb' command works when using a local postgres db for example.  But when using RDS I couldn't get it working.  You can use a different tool to automate the spinup of a RDS db e.g. terraform.

**Comment by tristanmorgan** [comment]
This issue seems to be stale. I've seen enough people running RDS with the app, so closing.
