### ISSUE TITLE
Issue in Postgres connecting to Docker

### ISSUE THREAD

**Issue by Ravihpr** [servian/TechChallengeApp#44]
### Subject of the issue
Fail to Connect to Postgres from Docker 18.0 application
Describe your issue here.

### Your environment

* version of application
* version of golang
* version of postgres: 9.3 Above

### Steps to reproduce

Tell us how to reproduce this issue:
If you are using Postgres 9.3 above with docker 18 the connection to DB Fails

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by tristanmorgan** [comment]
Is there some more info about how this issue is occurring? My current testbed uses the latest docker build of the app (0.8.0) and postgres:10-alpine with a scripted started working reliably. Part of the challenge is how you would do this.
