### ISSUE TITLE
 Docker  container to postgres Azure DB(remote db) authentication error, issue db.go 

### ISSUE THREAD

**Issue by mothomas** [servian/TechChallengeApp#49]
### Subject of the issue
docker container unable to authenticate to azure postgresql DB  with provided variables.
Describe your issue here.
while docker container trying to connect to postgres db, db.go is expecting 'username@host' if we supply variable in in above mentioned format line 73 in db.go  OWNER is expecting 'username' format, this will cause  db creation will fail.
both values are supplied using same variable may causing issue.
 
### Your environment
Azure posgresql rdb
* version of application
 TechTestApp version 0.5.0
* version of golang
* version of postgres
9.5

### Steps to reproduce
reproducible
clone repo, build and run container
in azure env with postgresql db integration will fail
Tell us how to reproduce this issue

### Expected behaviour
containered app should be able to provision azure postgresql database
Tell us what should happen

### Actual behaviour
containered app not able to provision azure postgresql database
Tell us what happens instead

**Comment by tristanmorgan** [comment]
I haven't been able to reproduce this one myself or heard any more reports of it. Please feel free to reopen if its still occurring.
