### ISSUE TITLE
dep is used for dependency management in golang [official link] for windows is broken

### ISSUE THREAD

**Issue by atulkumarpccs** [servian/TechChallengeApp#67]
### Windows dependency management link is broken

as we click on the [official link] it will direct us to 
https://github.com/golang/dep which is working but see the below [go.equinox.io] is broken

On Windows, you can download a tarball from go.equinox.io. 

### Windows 10

* version of application >>v.0.7.0
* version of golang >>go1.15.8
* version of postgres>>Not installed yet

### Steps to reproduce

as we click on the [official link] it will direct us to 
https://github.com/golang/dep which is working but see the below [go.equinox.io] is broken

On Windows, you can download a tarball from go.equinox.io. 

### the link should be updated or for windows where the end-user can download the package

Tell us what should happen

### End-user can download the dependency package so not able to build on windows

Tell us what happens instead

**Comment by atulkumarpccs** [comment]
![image](https://user-images.githubusercontent.com/13286642/107143557-d599e200-6989-11eb-8ba1-4e52f10c8b4b.png)

**Comment by tristanmorgan** [comment]
Quoting from [Dep's repo](https://github.com/golang/dep#dep)

> NOTE: Dep was an official experiment to implement a package manager for Go. As of 2020, Dep is deprecated and archived in favor of Go modules, which have had official support since Go 1.11. For more details, see https://golang.org/ref/mod.

for this reason I am going to close this issue.

**Comment by atulkumarpccs** [comment]
@tristanmorgan  is there is any dependency that is resolved by a dev or end-user can build the project without the use of any dependency package

**Comment by tristanmorgan** [comment]
Personally I usually the Docker container and when needed build inside one and cross compile for other targets. that being said there are precompiled version for Windows from the [releases page](https://github.com/servian/TechChallengeApp/releases/latest).
To build I ran the following commands:
```
$ docker run --rm -it -v ${PWD}:/go/src/github.com/servian/TechChallengeApp/ -w /go/src/github.com/servian/TechChallengeApp/ golang:alpine 
--- the inside the container ---
# apk add --no-cache git alpine-sdk
# go mod tidy
# CGO_ENABLED="0" go build -ldflags="-s -w" -a -o ./TechChallengeApp
```
I hope this helps.
