### ISSUE TITLE
Permission to servian/TechChallengeApp.git denied 

### ISSUE THREAD

**Issue by sweet-aus** [servian/TechChallengeApp#69]
### Subject of the issue

Permission to servian/TechChallengeApp.git denied to sweet-aus.

### Your environment
servian/TechChallengeApp

### Describe in details
Found minor errors in 12 different files.
✖License
✖root.go
✖serve.go
✖updatedb.go
✖config.go
✖deamon.go
✖db.go
✖main.go
✖task.go
✖api.go
✖index.go
✖ui.go

### Steps to reproduce
 ✅ Clone the repo
 ✅ Create a new branch
 ✅Go through the code
 ✅ Troubleshoot and update the code locally
 ✅ Push the code

### Expected behaviour
Unable to push the code to the repository.

### Actual behaviour
Permission to servian/TechChallengeApp.git denied 

Let's arrange a meeting and discuss about this.

**Comment by tristanmorgan** [comment]
Hi @sweet-aus,

I'm sorry but only Servian employees are expected to have write access to this repo. Others are free to make a fork of the repo, commit their changes to it and then create a pull request. (if you are an employee, please reach out to me on our internal chat so I can arrange to fix up your access).

What were the minor errors you found in those 12 files? Please feel free to create a PR (pull request) or explain further in this issue.

T.
