### ISSUE TITLE
> ### Description

### ISSUE THREAD

**Issue by lex2491** [servian/TechChallengeApp#73]
> ### Description
> Updates to the documentation to emphasise the app is already built. Also I updated the build scripts for a more consistent build output and removed references to dep.
> 
> Fixes: time wasted building the app.
> 
> ### Checklist
> * [x]  Code compiles correctly
> * [x]  Created tests which fail without the change (if possible)
> * [x]  All tests passing
> * [x]  Extended the README / documentation, if necessary
> * [x]  Added issue number to `Fixes` line above

_Originally posted by @lex2491 in https://github.com/servian/TechChallengeApp/issues/72#issuecomment-816296738_

**Comment by TWinsnes** [comment]
merged
