### ISSUE TITLE
Reread

### ISSUE THREAD

**Issue by lex2491** [servian/TechChallengeApp#74]
### Subject of the issue

Describe your issue here.

### Your environment

* version of application
* version of golang
* version of postgres

### Steps to reproduce

Tell us how to reproduce this issue

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by TWinsnes** [comment]
This is empty

**Comment by lex2491** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
