### ISSUE TITLE
Unable to create seed test data | Azure pgsql not liking username without @

### ISSUE THREAD

**Issue by nehagargSeequent** [servian/TechChallengeApp#89]
### Subject of the issue

I am unable to create seed test database in my Azure PostgreSQL server. An error is thrown by CREATE DATABASE query in updatedb.go when the _owner_ has the format _username@hostname_. This format is expected from the pgsql server to be able to connect to it.

### Your environment

servian/TechChallengeApp

### Steps to reproduce

- Create Azure Postgresql server
- Update conf.toml with the server configuration
- Create seed database using _updatedb.go_

### Expected behaviour

I should be able to run below and create seed database in Azure Postgresql server.
`./TechChallengeApp updatedb`

### Actual behaviour
If I pass **DbUser without @**, Azure PostgreSQL does not like it. The app is unable to connect to database server.
![image](https://user-images.githubusercontent.com/81267312/144739590-f0ae834a-f3c7-4016-84a1-71f47ab0d788.png)

If I pass **DbUser with @**, updatedb.go does not like it. It fails at the CREATE DATABASE step,
![image](https://user-images.githubusercontent.com/81267312/144739582-bf02eae8-3043-4137-9d51-5c63382836aa.png)

![image](https://user-images.githubusercontent.com/81267312/144739560-b9c4c928-444a-4195-9807-9507093828c3.png)

**Comment by tristanmorgan** [comment]
Hi @nehagargSeequent 

There have been a number of Candidates working with Azure's implementation of PostgreSQL that used an '@' symbol to separate the user and host. Also part of the challenge is understanding when a cloud's database implementation gives you the ability to drop the whole database or not, and looking at the help messages of a black-box application to find workarounds.

Below is the help message from the application, I hope this provides the clue.
```
$ docker run --rm -it servian/techchallengeapp updatedb -h
Updates DB that has been defined in the configuration file. If no db exist, one will be created

Usage:
  TechChallengeApp updatedb [flags]

Flags:
  -h, --help             help for updatedb
  -s, --skip-create-db   Use to skip the creation of the database
```
Ref: #20
